### ISSUE TITLE
Consider merging with shssoichiro/zxcvbn-rs

### ISSUE THREAD

**Issue by vks** [xd009642/zxcvbn-rs#1]
There is also [shssoichiro/zxcvbn-rs](https://github.com/shssoichiro/zxcvbn-rs), maybe the two projects can be merged?

**Comment by xd009642** [comment]
So this project is unmaintained and I didn't publish it to crates.io because of [shssoichiro/zxcvbn-rs](https://github.com/shssoichiro/zxcvbn-rs). I created this project to help me initially learn Rust and now just use it to experiment with different tools with travis etc. 

Given all that I don't really have any interest in working on it actively or looking to see if there are any elements of my implementation shssoichiro would benefit from. The license is MIT/Apache is anyone is welcome to take any elements they like and reusing them elsewhere though :smile:

**Comment by vks** [comment]
Thanks for the clarification! I opened a pull request with a suggested update to the README.
